-- CreateEnum
CREATE TYPE "ConcertCategory" AS ENUM ('EDM_DJ_EVENTS', 'GLOBAL_ARENA_STARS', 'LOCAL_REGIONAL_SHOWS', 'CLASSICAL_ORCHESTRAL', 'FESTIVALS_MULTI_DAY');

-- AlterTable
ALTER TABLE "Concert" ADD COLUMN     "category" "ConcertCategory" NOT NULL DEFAULT 'LOCAL_REGIONAL_SHOWS';
